### ISSUE TITLE
Почему такое особое внимание именно 0-му элементу?

### ISSUE THREAD

**Issue by coursar** [NURGALIMOV/jdbc-template#2]
https://github.com/NURGALIMOV/jdbc-template/blob/a42c36d215282cf4f843678ae53e29b83530f3f6/src/main/java/ru/inurgalimov/jdbc/JdbcTemplate.java#L51-L54

**Comment by NURGALIMOV** [comment]
У метода есть аргумент varArgs `args`, когда по отдельности присылаем объекты через запятую проблем нет. Но при отправке массивом Object[] он его видит как один объект, и у меня были проблемы при отправке параметров массивом, по этому добавил эту проверку на тот случай если придет массив.

**Comment by NURGALIMOV** [comment]
Убрал проверку, у меня была ошибка, на одном из уроков выясняли.
