### ISSUE TITLE
Где update?

### ISSUE THREAD

**Issue by coursar** [NURGALIMOV/jdbc-template#4]
https://github.com/NURGALIMOV/jdbc-template/blob/a42c36d215282cf4f843678ae53e29b83530f3f6/src/main/java/ru/inurgalimov/jdbc/JdbcTemplate.java#L11

**Comment by NURGALIMOV** [comment]
Я предполагал что эти методы будут делать все операции CRUD, хотел прислать еще на проверку применение JdbcTemplate, но не успел прислать на проверку. Дошлю попозже...

**Comment by NURGALIMOV** [comment]
В рамках https://github.com/NURGALIMOV/spring-mvc использовал методы query или querySingle из  JdbcTemplate
